name: Test

on:
  push:
    branches:
    - main
  pull_request:
jobs:
  test:
    permissions:
      # to allow octocov to report comment
      pull-requests: write
    uses: lufia/workflows/.github/workflows/go-test.yml@cover
